on: workflow_dispatch

jobs:
  test_job:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          sparse-checkout: |
            test.py
            test.txt
          sparse-checkout-cone-mode: false
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11' 
      - run: |
          ls
          python test.py
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add --all
          git commit -m "action test commit"
          git push
