on:
  workflow_dispatch:
    inputs:
      mc_version:
        type: string
        default: latest-release

jobs:
  test_job:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11' 
      - run: |
          git init
          git config user.name actions-user
          git config user.email actions@github.com
          git remote add origin https://x-access-token:${{ github.token }}@github.com/$GITHUB_REPOSITORY
      - run: |
          git status
          git fetch origin
          git branch
      - run: |
          git status
          git reset origin/testbranch
      - run: |
          git status
          git add --all
          git commit -m "action test commit"
      - run: |
          git status
          git push origin master:testbranch
      - run: |
          git status

# python test.py ${{ inputs.mc_version }}
