on:
  workflow_dispatch:
    inputs:
      mc_version:
        type: string
        default: latest-release

jobs:
  test_job:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11' 
      - run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git symbolic-ref HEAD refs/heads/testbranch
          git reset
          python test.py ${{ inputs.mc_version }}
          git add --all
          git commit -m "action test commit"
          git push
